version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo $TAG
      - IMAGE_URI="${REPOSITORY}:${TAG}"
      - echo $IMAGE_URI
  build:
    commands:
      - echo $IMAGE_URI
      - echo ${REPOSITORY}
      - echo $TAG
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"simpleapp","imageUri":"%s"}]' $IMAGE_URI > image.json
      - 'cat image.json'
artifacts:
  files: 
    - image.json
    # - cfn/service.yml
    # - cfn/environments/production.json
  #discard-paths: yes