version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY}:${TAG}"
  build:
    commands:
      - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '{"Image":"%s"}' $IMAGE_URI > images.json
artifacts:
  files: 
    - images.json
    - cfn/services.yml
    - cfn/environments/production.json
  discard-paths: yes
